# config/k8s/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud14-app
  labels:
    app: cloud14-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud14-app
  template:
    metadata:
      labels:
        app: cloud14-app
    spec:
      containers:
        - name: cloud14-app
          image: 474668424273.dkr.ecr.ap-southeast-1.amazonaws.com/cloud14  # Placeholder for the Docker image URI
          ports:
            - containerPort: 3000
