# config/k8s/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 781655249241.dkr.ecr.us-east-1.amazonaws.com/flora-argocd-ecr-demo:latest  # Placeholder for the Docker image URI
          ports:
            - containerPort: 8080