# config/k8s/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinisys-webapp
  labels:
    app: infinisys-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infinisys-webapp
  template:
    metadata:
      labels:
        app: infinisys-webapp
    spec:
      containers:
        - name: infinisys-webapp
          image: 642588679360.dkr.ecr.us-east-1.amazonaws.com/infinisys-webapp:latest  # Placeholder for the Docker image URI
          ports:
            - containerPort: 8080