# config/k8s/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-argocd-app
  labels:
    app: my-argocd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-argocd-app
  template:
    metadata:
      labels:
        app: my-argocd-app
    spec:
      containers:
        - name: my-argocd-app
          image: 642588679360.dkr.ecr.us-west-2.amazonaws.com/flo-ecr-repo:latest  # Placeholder for the Docker image URI
          ports:
            - containerPort: 3000