# config/k8s/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: infinisys-webapp-service
spec:
  selector:
    app: infinisys-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
