# config/k8s/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: my-argocd-app-service
spec:
  selector:
    app: cloud14-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
