apiVersion: v1
clusters:
- cluster:
    server: https://2D1C58C89CE91F7D21A43CBD5F8A946E.gr7.us-east-1.eks.amazonaws.com
    certificate-authority-data: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIHNlcnZlcjogaHR0cHM6Ly8yRDFDNThDODlDRTkxRjdEMjFBNDNDQkQ1RjhBOTQ2RS5ncjcudXMtZWFzdC0xLmVrcy5hbWF6b25hd3MuY29tCiAgICBjZXJ0aWZpY2F0ZS1hdXRob3JpdHktZGF0YTogPGJhc2U2NC1jYS1jZXJ0PgogIG5hbWU6IG15LWFwcC1jbHVzdGVyCmNvbnRleHRzOgotIGNvbnRleHQ6CiAgICBjbHVzdGVyOiBteS1hcHAtY2x1c3RlcgogICAgdXNlcjogRmxvcmEtQWRtaW4KICBuYW1lOiBteS1jb250ZXh0CmN1cnJlbnQtY29udGV4dDogbXktY29udGV4dApraW5kOiBDb25maWcKdXNlcnM6Ci0gbmFtZTogRmxvcmEtQWRtaW4KICB1c2VyOgogICAgdG9rZW46IDxhdXRoLXRva2VuPgo=
  name: my-app-cluster
contexts:
- context:
    cluster: my-app-cluster
    user: Flora-Admin
  name: my-context
current-context: my-context
kind: Config
users:
- name: Flora-Admin
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InFVVFdEaXp4aXoxQjZfZDRITVpiZS01NVBhZE5LT2JjQXV1cUNtbWphbzQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Im15LXNlcnZpY2UtYWNjb3VudC10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJteS1zZXJ2aWNlLWFjY291bnQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIwYjM3MjYzMi0xZTE4LTRhMDgtODRkZi1iYjRjNjlhYzM4MGYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpteS1zZXJ2aWNlLWFjY291bnQifQ.MaG9ih-MWbWaC97z6FNH8RDj0Tbx7TR9amEvIvrVDj0J75_yg_dKrwQdLTqgM6g0NPgOwnoSppkcw1oXKvt8grwjCK1TVRQuN6yeVEv4CPznu773p5dexoS7VeglmLzTz2uZNAfsbV9GCHqgNABeMKHJ1fzW7bKNE37ltrHjPpojLqK6mBGVmoAeB6gSWQhOOZhG-N4uW0DSFSJA1q5WOzCqTPG3_JQtjnUhZbe0NLCRP4kE28-tR2kJpQn2hKKwFXpZHDqYPKTBF083U95wvZ2rAF9RpvXvoq-69w1KitZg5djSw2PKoas8oCUe99ePyBxI4yimWs5aGoA6YMBSMg
