apiVersion: v1
clusters:
- cluster:
    server: https://2D1C58C89CE91F7D21A43CBD5F8A946E.gr7.us-east-1.eks.amazonaws.com
    certificate-authority: /home/runner/work/my-argocd-app/config/kubeconfig/ca.crt
  name: flo-eks-cluster
contexts:
- context:
    cluster: flo-eks-cluster
    user: Flora
  name: my-argocd-context
current-context: my-argocd-context
kind: Config
users:
- name: Flora
  user:
    token: ${KUBE_CONFIG_DATA}