apiVersion: v1
clusters:
- cluster:
    server: https://2D1C58C89CE91F7D21A43CBD5F8A946E.gr7.us-east-1.eks.amazonaws.com
    certificate-authority-data: <base64-ca-cert>
  name: my-app-cluster
contexts:
- context:
    cluster: my-app-cluster
    user: Flora-Admin
  name: my-context
current-context: my-context
kind: Config
users:
- name: Flora-Admin
  user:
    token: <auth-token>
