apiVersion: v1
clusters:
- cluster:
    server: https://2D1C58C89CE91F7D21A43CBD5F8A946E.gr7.us-east-1.eks.amazonaws.com
    certificate-authority: /home/runner/work/infinisys-webapp/config/kubeconfig/ca.crt
  name: infinisys-eks-cluster
contexts:
- context:
    cluster: infinisys-eks-cluster
    user: Flora
  name: infinisys-context
current-context: infinisys-context
kind: Config
users:
- name: Flora
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjEyWW1jOVZvUEQ0S0hwNlZGWkNNYVk2Q3dsTnU3TEtvSkRWVUhnd25PYzQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiYXJnb2NkLXN2Yy1hY2NvdW50LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFyZ29jZC1zdmMtYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjZmMGNiYTY1LWI0YmQtNGNkYi05NDYzLTA5MjkyYzJkYjY2MCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDphcmdvY2Q6YXJnb2NkLXN2Yy1hY2NvdW50In0.iyDDAiNanBs5psatnDgv2I4Yxo5NlK05YZceutSzdt7ouMLFmQFFRcoKf9HE4oGEjhoMNPZCArTQHh9vAOiiyFQEbQG509q5CDpcLdOsZDBwMdv0zJ_50lgflnIxDDLRUNNagVDb7UfVwXBIMX_hDZHvb7CMAaQ3_41cVEgFXTtUP6aBFwDGPtD0490licz663QhNDuGQz4cIPfU5SB0oiD0Rpme6J0dcpO7ZcDF3gW6ASi3A8BLNmmAQljqv5YGOewxQ_YtxTMWDRfwi1HHZ6qGOGBwkgJ947_X_kG5d710pxVBgGvCfxZKXdP3guFwMHzIEEFX9A_SxFktOKbdiQ