apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-argocd-app
  labels:
    app: my-argocd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-argocd-app
  template:
    metadata:
      labels:
        app: my-argocd-app
    spec:
      containers:
      - name: my-argocd-app
        image: <781655249241>.dkr.ecr.<us-east-1>.amazonaws.com/my-argocd-app:latest
        ports:
        - containerPort: 80
