name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install ArgoCD CLI
        run: |
          echo "Installing ArgoCD CLI..."
          sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd

      - name: Upgrade npm to v11.0.0
        run: npm install -g npm@11.0.0

      - name: Clear npm Cache
        run: |
          npm cache clean --force
          npm cache verify

      - name: Regenerate Dependencies
        run: |
          rm -rf ./app/package-lock.json ./app/node_modules
          npm set registry https://registry.npmjs.org/
          npm install --prefix ./app

      - name: Cache Node.js Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm-force-resolutions
        run: |
          npm install npm-force-resolutions --save-dev

      - name: Install and Audit Dependencies
        run: |
          npx npm-force-resolutions
          npm install --prefix ./app
          npm audit fix --prefix ./app

      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker build --no-cache -t infinisys-webapp:latest ./app

      - name: Tag Docker Image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          VERSION=$(git rev-parse --short HEAD)
          docker tag infinisys-webapp:latest $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
          docker tag infinisys-webapp:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Authenticate with AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Push Docker Image to ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          VERSION=$(git rev-parse --short HEAD)
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Create Snyk Policy File
        run: |
          mkdir -p ./infinisys-webapp
          echo "ignore:
            SNYK-JS-CROSSSPAWN-8303230:
              - '*':
                  reason: 'Temporary ignore until resolved in upstream dependencies'
                  expires: '2024-12-31T00:00:00Z'" > ./infinisys-webapp/.snyk

      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      - name: Run Snyk Scan
        run: |
          snyk test --file=./app/package.json --policy-path=./infinisys-webapp --severity-threshold=medium --docker ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  deploy-to-eks:
    runs-on: ubuntu-latest
    needs: build-and-scan

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install ArgoCD CLI
      - name: Install ArgoCD CLI
        run: |
          echo "Installing ArgoCD CLI..."
          sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd

      # Step 3: Test ArgoCD Server Connectivity
      - name: Verify ArgoCD Server Connectivity
        run: |
          echo "Testing connectivity to ArgoCD server..."
          curl -I https://ab575c8c888554c6bba2f6fc32474309-427562321.us-east-1.elb.amazonaws.com --insecure

      # Step 4: Configure AWS CLI and kubeconfig for EKS
      - name: Configure AWS CLI and kubeconfig
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name infinisys-eks-cluster

          kubectl get nodes  # Verify connection

      # Step 5: Login to ArgoCD with Persistent Session
      - name: ArgoCD Login
        run: |
          echo "Logging into ArgoCD..."
          argocd login ab575c8c888554c6bba2f6fc32474309-427562321.us-east-1.elb.amazonaws.com \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --grpc-web \
            --insecure  # Bypass SSL certificate verification

      # Step 6: Verify ArgoCD Login Session
      - name: Verify ArgoCD Session
        run: |
          echo "Verifying ArgoCD session..."
          argocd account get-user-info \
            --server ab575c8c888554c6bba2f6fc32474309-427562321.us-east-1.elb.amazonaws.com \
            --grpc-web \
            --insecure

      # Step 7: Trigger ArgoCD Sync with Application Status Check
      - name: Trigger ArgoCD Sync
        run: |
          echo "Synchronizing ArgoCD application..."
          # Check application status first
          argocd app get infinisys-webapp \
            --grpc-web \
            --insecure \
            --server ab575c8c888554c6bba2f6fc32474309-427562321.us-east-1.elb.amazonaws.com
          # Proceed with sync
          argocd app sync infinisys-webapp \
            --grpc-web \
            --insecure \
            --server ab575c8c888554c6bba2f6fc32474309-427562321.us-east-1.elb.amazonaws.com

      # Step 8: Add Debugging Steps
      - name: Debug Environment
        run: |
          echo "Checking Git Configuration"
          git config --list
          echo "Checking Environment Variables"
          printenv
