name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Directory Listing
        uses: ./.github/workflows/reusable-list-directories.yml
        with:
          paths: |
            [
              "my-argocd-app",
              "my-argocd-app/config",
              "my-argocd-app/config/kubeconfig"
            ]

      - name: Install Argo CD CLI
        run: |
          echo "Installing Argo CD CLI..."
          sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd

      - name: Argo CD Login and Sync
        run: |
          echo "Logging into Argo CD and synchronizing the application..."
          for i in {1..5}; do
            argocd login ${{ secrets.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --grpc-web --insecure && break || sleep 15;
          done
          argocd app sync my-app --grpc-web --insecure
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Clear npm Cache
        run: |
          echo "Clearing npm cache..."
          npm cache clean --force
          npm cache verify

      - name: Regenerate Dependencies
        run: |
          echo "Reinstalling dependencies..."
          rm -rf ./app/package-lock.json ./app/node_modules
          npm set registry https://registry.npmjs.org/
          npm install --prefix ./app

      - name: Cache Node.js Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm-force-resolutions
        run: |
          echo "Installing npm-force-resolutions..."
          npm install npm-force-resolutions --save-dev

      - name: Install and Audit Dependencies
        run: |
          echo "Running npm audit fix and resolving vulnerabilities..."
          npx npm-force-resolutions
          npm install --prefix ./app
          npm audit fix --prefix ./app

      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          echo "Building Docker image..."
          docker build --no-cache -t my-app:latest ./app

      - name: Tag Docker Image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "Tagging Docker image with version $VERSION and latest tag..."
          docker tag my-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
          docker tag my-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Authenticate with AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "Authenticating with AWS ECR..."
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Push Docker Image to ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "Pushing Docker image to ECR with version $VERSION..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Snyk Scan
        run: |
          echo "Running Snyk scan..."
          snyk test --file=./app/package.json --policy-path=./my-argocd-app --severity-threshold=medium --docker ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  deploy-to-eks:
    runs-on: ubuntu-latest
    needs: build-and-scan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Directory Listing
        uses: ./.github/workflows/reusable-list-directories.yml
        with:
          paths: |
            [
              "my-argocd-app",
              "my-argocd-app/config",
              "my-argocd-app/config/kubeconfig"
            ]

      - name: Set up kubeconfig
        run: |
          echo "Setting up kubeconfig..."
          mkdir -p ~/.kube
          cp my-argocd-app/config/kubeconfig/kubeconfig.yaml ~/.kube/config
          kubectl config view
          kubectl cluster-info

      - name: Debug Kubernetes Access
        run: |
          echo "Debugging Kubernetes access..."
          kubectl get nodes
          kubectl get namespaces
          kubectl get deployments --all-namespaces

      - name: Update Kubernetes Manifests
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "Updating Kubernetes manifests with image $VERSION..."
          sed -i "s|image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION|g" ./config/k8s/deployment.yaml

      - name: Apply Kubernetes Deployment
        run: |
          echo "Applying Kubernetes deployment..."
          kubectl apply -f ./config/k8s/deployment.yaml --validate=true

      - name: Verify Deployment Rollout
        run: |
          echo "Verifying Kubernetes deployment rollout..."
          kubectl rollout status deployment/my-app -n my-namespace
