name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      env:
        AWS_REGION: <us-east-1>
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com

    - name: Build, Tag, and Push Docker Image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t my-argocd-app .
        docker tag my-argocd-app:latest <781655249241>.dkr.ecr.<us-east-1>.amazonaws.com/my-argocd-app:${{ github.sha }}
        docker push <781655249241>.dkr.ecr.<us-east-1>.amazonaws.com/my-argocd-app:${{ github.sha }}

    - name: Update Kubernetes Manifests
      run: |
        sed -i "s/latest/${{ github.sha }}/g" manifests/deployment.yaml
        git config --global user.email "fyuyuun@gmail.com"
        git config --global user.name "florayuyuun123"
        git add manifests/deployment.yaml
        git commit -m "Update image version to ${{ github.sha }}"
        git push origin main

    - name: Run Snyk Security Scan
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: <781655249241>.dkr.ecr.<us-east-1>.amazonaws.com/my-argocd-app:${{ github.sha }}
